### ISSUE TITLE
新規ドメインの購入について

### ISSUE THREAD

**Issue by sh4869** [tokyotechnicalsamurai/tokyotechnicalsamurai.github.io#17]
* どのドメインを取るか
* いつ取るか
* 誰が買うか

**Comment by sh4869** [comment]
どのドメインを購入するのかという話を僕にしてくれれば、こちらで購入してあとから金額だけ請求するという形を取ることは可能です

**Comment by sh4869** [comment]
@asannkkh ドメイン決定の会議などは早くていつ頃出来そうですか?

**Comment by asannkkh** [comment]
必要なのかという議論になってしまったのですが

**Comment by sh4869** [comment]
そこはそちらに任せます。

* 信頼性の確保(mlより馴染みのあるトップレベルドメインにすることでサイトの信頼感を増す)
* ドメイン名の短縮
* 多少奇をてらったものを購入することによってのパフォーマンス効果

というような利点と、

* 変えるコストがかかる(購入費・いろいろな場所のリンク)
* 変えることによる混乱

といった不利益もありますし。忙しい時期ですし、交渉始まっちゃいましたしね。

**Comment by sh4869** [comment]
なるべく早めにどうするのか決めて、9/24の夜23:59までに伝えてください。

**Comment by sh4869** [comment]
@asannkkh 話し合ってますか～?

**Comment by asannkkh** [comment]
今回は見送ることにしました

**Comment by sh4869** [comment]
了解です
